
"use client";

import React from 'react';
import Container from '@/components/layout/Container';
import { GlassCard, GlassCardContent, GlassCardHeader, GlassCardTitle } from '@/components/shared/GlassCard';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { HelpCircle } from 'lucide-react';

const faqs = [
  {
    question: "What is the Prompt Generator and how does it work?",
    answer: "The Prompt Generator is BrieflyAI's core feature for creating new prompts from scratch. You start by defining a clear goal. The app's AI then generates a dynamic, adaptive survey with tailored questions to gather the necessary context, tone, and desired format. Your answers are then used to engineer a highly optimized and effective prompt.",
  },
  {
    question: "What is the Prompt Vault?",
    answer: "The Prompt Vault is your personal, cloud-based library for all saved prompts. Every time you create and save a prompt, it's stored here. The vault allows you to easily search, sort, and manage your entire history, making it simple to find and reuse your most effective prompts.",
  },
  {
    question: "How does the Prompt Refinement Hub work?",
    answer: "The Refinement Hub allows you to iterate on your saved prompts. You can select any prompt from your vault to manually edit its details. Crucially, you can also request AI-powered suggestions. The AI analyzes your prompt in the context of your past successful prompts to provide unique, actionable tips for improvement.",
  },
  {
    question: "What does the Model-Specific Prompts feature do?",
    answer: "Different AI models have different strengths. This feature adapts a general prompt to make it highly effective for a specific model (e.g., GPT-4 for text, DALL-E 3 for images, or Midjourney for artistic styles). It adjusts the syntax and structure and provides tips for getting the best results from your chosen model.",
  },
   {
    question: "What is Contextual Prompting?",
    answer: "This tool generates new prompts based on existing content. You can paste a document, an email, or any piece of text, and the AI will analyze it to create a relevant prompt. This is useful for summarizing text, asking follow-up questions, or expanding on ideas within the document.",
  },
  {
    question: "What is the Prompt Academy?",
    answer: "The Prompt Academy is an educational section designed to help you master prompt engineering. It contains articles, best practices, and tutorials on the fundamental principles of crafting effective prompts, helping you improve your skills.",
  },
  {
    question: "How do Real-Time AI Suggestions work?",
    answer: "As you type a prompt into the dedicated text area on this page, BrieflyAI's AI assistant works in the background. After a brief pause in your typing, it automatically provides suggestions to enhance clarity, add detail, or improve the structure of your prompt-in-progress.",
  },
  {
    question: "What is Prompt Feedback & Analysis?",
    answer: "This tool acts as a quality check for your prompts. You submit a prompt, and the AI analyzes it based on criteria like clarity, specificity, and actionability. It then provides a numerical quality score out of 10 and a list of specific, actionable feedback items to help you improve it.",
  },
  {
    question: "How does Reverse Prompting work?",
    answer: "If you have a piece of text that was generated by an AI, you can use this feature to figure out what the original prompt might have been. Paste the AI's output, and our tool will reverse-engineer a plausible prompt that could have produced that result.",
  },
  {
    question: "What is the Prompt Analytics Dashboard?",
    answer: "The Analytics Dashboard provides insights into your prompting activity. It visualizes key metrics such as your total number of saved prompts, your average prompt quality score over time, and your most frequently used AI models, helping you track your improvement and habits.",
  },
  {
    question: "What is Prompt Learning Mode?",
    answer: "This page explains the philosophy behind BrieflyAI. Our platform is designed to learn from your interactions. By analyzing the prompts you save, refine, and score, our system can provide increasingly personalized and effective suggestions over time, tailored to what works for you.",
  },
  {
    question: "What is the AI Model Compatibility Checker?",
    answer: "This feature helps ensure your prompt is suitable for your target AI model. It checks for mismatches (e.g., asking an image model to write text) and provides feedback. It uses the same underlying technology as the Model-Specific Prompts feature to adapt your prompt for the best performance.",
  },
    {
    question: "What is the Support Assistant?",
    answer: "The Support Assistant is an AI-powered chatbot, available on your dashboard, designed to answer your questions about using BrieflyAI's features. For sensitive issues like billing or security, it will guide you to contact human support.",
  },
    {
    question: "What is the Quick Refine tool?",
    answer: "The Quick Refine tool is a floating assistant accessible from your dashboard. It allows you to quickly input a raw idea or thought, and it will instantly return a polished, optimized prompt that is automatically copied to your clipboard for immediate use.",
  },
];

export function FAQSection() {
  return (
    <section id="faq" className="py-16 md:py-24 bg-gradient-to-b from-background via-indigo-50/5 to-background">
      <Container>
        <div className="text-center mb-12 md:mb-16">
          <HelpCircle className="h-12 w-12 text-primary mx-auto mb-4" />
          <h2 className="font-headline text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            BrieflyAI Feature Overview
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-lg text-muted-foreground">
            Find answers to common questions about BrieflyAI's capabilities.
          </p>
        </div>

        <GlassCard className="max-w-3xl mx-auto p-0 md:p-2 border-border/30">
          <GlassCardContent className="p-4 md:p-6">
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, index) => (
                <AccordionItem key={index} value={`item-${index}`} className="border-b-border/50">
                  <AccordionTrigger className="text-left hover:no-underline">
                    <span className="font-medium text-foreground text-md">{faq.question}</span>
                  </AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground text-sm leading-relaxed whitespace-pre-line">
                      {faq.answer}
                    </p>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </GlassCardContent>
        </GlassCard>
      </Container>
    </section>
  );
}
