
"use client";

import React from 'react';
import { MainHeader } from '@/components/layout/MainHeader';
import { Footer } from '@/components/layout/Footer';
import Container from '@/components/layout/Container';
import { GlassCard, GlassCardContent, GlassCardHeader, GlassCardTitle } from '@/components/shared/GlassCard';

export default function TermsOfServicePage() {
  // Using a static date to prevent hydration mismatches.
  // This value should be updated manually when the terms change.
  const lastUpdatedDate = "June 12, 2025";
  const supportEmail = process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'babseli933@gmail.com';

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <MainHeader />
      <main className="flex-grow py-12 md:py-16">
        <Container>
          <GlassCard className="max-w-3xl mx-auto">
            <GlassCardHeader>
              <GlassCardTitle className="font-headline text-3xl">Terms of Service</GlassCardTitle>
            </GlassCardHeader>
            <GlassCardContent className="prose prose-indigo dark:prose-invert max-w-none">
              <p><em>Last Updated: {lastUpdatedDate}</em></p>

              <h2>1. Agreement to Terms</h2>
              <p>By using BrieflyAI ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.</p>

              <h2>2. Description of Service</h2>
              <p>BrieflyAI is a SaaS application that provides AI-powered prompt optimization tools. Users can input goals, answer adaptive survey questions, and receive optimized prompts.</p>

              <h2>3. User Accounts</h2>
              <p>To use certain features of the Service, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete. You are responsible for safeguarding your password and for all activities that occur under your account.</p>

              <h2>4. User Content</h2>
              <p>You retain ownership of any intellectual property rights that you hold in the content you submit to the Service (e.g., your goals, survey answers, and generated prompts). By submitting content, you grant BrieflyAI a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and display such content solely for the purpose of providing and improving the Service.</p>
              <p>You are solely responsible for the content you submit and ensure that it does not violate any laws or third-party rights.</p>
              
              <h2>5. Use of AI Models</h2>
              <p>The Service utilizes third-party AI models (e.g., OpenAI) to optimize prompts. Your interaction with these AI models through our Service is subject to the terms and policies of those third-party providers. We are not responsible for the output generated by these AI models.</p>

              <h2>6. Subscriptions and Payments</h2>
              <p>Certain features of the Service may be available only through a paid subscription. Subscription fees are processed through Paystack. All fees are non-refundable except as required by law or as explicitly stated in our refund policy. You are responsible for all applicable taxes.</p>
              <p>We reserve the right to change our subscription plans and pricing at any time. We will provide reasonable notice of any such changes.</p>

              <h2>7. Acceptable Use</h2>
              <p>You agree not to use the Service for any unlawful purpose or in any way that interrupts, damages, or impairs the Service. Prohibited activities include, but are not limited to: attempting to gain unauthorized access to the Service, transmitting viruses or malicious code, and engaging in any activity that is harmful, fraudulent, or abusive.</p>

              <h2>8. Termination</h2>
              <p>We may terminate or suspend your access to the Service at any time, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will immediately cease.</p>

              <h2>9. Disclaimers</h2>
              <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

              <h2>10. Limitation of Liability</h2>
              <p>TO THE FULLEST EXTENT PERMITTED BY LAW, BRIEFLYAI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR USE OF THE SERVICE; (B) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY PERSONAL INFORMATION STORED THEREIN.</p>

              <h2>11. Governing Law</h2>
              <p>These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law principles.</p>

              <h2>12. Changes to Terms</h2>
              <p>We reserve the right to modify these Terms at any time. We will provide notice of such changes by posting the updated Terms on our website. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.</p>

              <h2>13. Contact Us</h2>
              <p>If you have any questions about these Terms, please contact us at {supportEmail}.</p>
            </GlassCardContent>
          </GlassCard>
        </Container>
      </main>
      <Footer />
    </div>
  );
}
